# Generated by Django 3.2.18 on 2023-06-19 21:17

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='item',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default/no_image.jpg', max_length=255, null=True, upload_to=store.models.Item.image_upload_to),
        ),
    ]
