# Generated by Django 3.2.18 on 2023-06-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('draft ', 'draft'), ('waitingapproval ', 'waitingapproval'), ('active ', 'active '), ('deleted', 'deleted')], default='active ', max_length=50),
        ),
    ]
