# Generated by Django 3.2.18 on 2023-06-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('draft ', 'draft'), ('waitingapproval ', 'waitingapproval'), ('active ', 'active'), ('deleted', 'deleted')], default='active ', max_length=50),
        ),
    ]
