# Generated by Django 3.2.18 on 2023-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/item_images/thumbnail/'),
        ),
    ]
