# Generated by Django 3.2.18 on 2023-07-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
