# Generated by Django 3.2.18 on 2023-07-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
