# Generated by Django 3.2.18 on 2023-03-28 10:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    #operations = [
       # migrations.AddField(
            #model_name='item',
            #name='image',
            #field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=core.models.Item.image_upload_to),
        #),
    #]
