# Generated by Django 3.2.18 on 2023-04-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Aphrodisiac '), ('PB', 'Power Booster'), ('T', 'Tea'), ('HS', 'Herbal Supliments'), ('M', 'Medicine'), ('E', 'Essence '), ('D', 'Distilate '), ('V', 'Viaga '), ('TN', 'Tonics '), ('S', 'Supplements ')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('SO', 'Special offer'), ('R', 'Ramadan offer'), ('P', 'Promo'), ('PQ', 'Premium Quality '), ('NA', 'Naural')], max_length=2),
        ),
    ]
