# Generated by Django 3.2.18 on 2023-05-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
