# Generated by Django 3.2.18 on 2023-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Aphrodisiac '), ('PB', 'Power Booster'), ('T', 'Tea'), ('HS', 'Herbal Supliments'), ('M', 'Medicine'), ('E', 'Essence '), ('D', 'Distilate '), ('V', 'Viaga '), ('TN', 'Tonics '), ('S', 'Supplements ')], default=0, max_length=2),
        ),
    ]
