# Generated by Django 3.2.18 on 2023-06-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Aphrodisiac '), ('PB', 'Power Booster'), ('T', 'Tea'), ('HS', 'Herbal Supliments'), ('M', 'Medicine'), ('E', 'Essence '), ('D', 'Distilate '), ('V', 'Viaga '), ('TN', 'Tonics '), ('S', 'Supplements ')], max_length=2),
        ),
    ]
