# Generated by Django 3.2.18 on 2023-06-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230616_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='title',
        ),
    ]
