# Generated by Django 3.2.18 on 2023-05-31 12:50

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('A', 'Aphrodisiac '), ('PB', 'Power Booster'), ('T', 'Tea'), ('HS', 'Herbal Supliments'), ('M', 'Medicine'), ('E', 'Essence '), ('D', 'Distilate '), ('V', 'Viaga '), ('TN', 'Tonics '), ('S', 'Supplements ')], max_length=2)),
                ('label', models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('SO', 'Special offer'), ('R', 'Ramadan offer'), ('P', 'Promo'), ('PQ', 'Premium Quality '), ('NA', 'Naural')], max_length=2)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=category.models.Item.image_upload_to)),
            ],
        ),
    ]
