# Generated by Django 3.2.18 on 2023-05-31 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('A', 'Aphrodisiac '), ('PB', 'Power Booster'), ('T', 'Tea'), ('HS', 'Herbal Supliments'), ('M', 'Medicine'), ('E', 'Essence '), ('D', 'Distilate '), ('V', 'Viaga '), ('TN', 'Tonics '), ('S', 'Supplements ')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
